version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-ba-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-456123}
      POSTGRES_DB: aiba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./ai-ba-backend
      dockerfile: Dockerfile
    container_name: ai-ba-backend
    depends_on:
      - postgres
    environment:
      - PORT=9000
      - DB_DSN=
      # Add other environment variables here if needed
      - JWT_SECRET=
      - AI_KEY=
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./ai_analysc
      dockerfile: Dockerfile
    container_name: ai-ba-frontend
    depends_on:
      - backend
    # внутри контейнера фронт слушает 3000 (serve), наружу отдаём на 3001
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
